[package]
name = "pura_lingua_proc_macro_utils"
edition = "2024"
version.workspace = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }
proc-macro-crate = "3.3.0"
derive_more = { version = "2.0.1", features = ["from_str"] }
