[package]
name = "pura_lingua_v2_binary_proc_macros"
edition = "2024"
version.workspace = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
proc-macro-crate = "3.3.0"
proc_macro_utils = { workspace = true }

[lib]
proc-macro = true
